# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f36c216372c6184a5f995af70f2951256ca4f06a026f3272db0fc087a38f973410d69aeee8cd91dd8dfa2f49d60cef8ba4e2879ba57037e1eb1decab486ddf66

test:
  secret_key_base: c22a3735a3da6a8efcf5dbe79f5cace788799cdf46558efe9b16e95b4ad6d587ee8642b9a1c05624742ed1e80ac57b479c82e5336ba73a43ccfdb47b6aeb9ac1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
